# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIs/ui_final.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class FinalWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi()
        
    def setPlayersData(self, name1, pontos1, name2, pontos2):
        self.playerNomeLabel.setText(name1)
        self.playerNomeLabel_2.setText(name2)
        self.pontosLabel.setText(str(pontos1))
        self.pontosLabel_2.setText(str(pontos2))
        
    def setWinner(self, name1, pontos1, name2, pontos2):
        winner = None
        if int(pontos1) > int(pontos2):
            winner = name1
        elif int(pontos1) < int(pontos2):
            winner = name2
        
        if winner:
            self.campeaoLabel.setText(f"{winner} ganhou")
        else:
            self.campeaoLabel.setText("Houve um empate")

    def setupUi(self):
        self.setObjectName("FinalWindow")
        self.resize(1366, 768)
        self.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget()
        self.centralwidget.setStyleSheet("QLabel {color: #fff;}\n"
"\n"
"#player1Widget  {\n"
"    border: 2px solid #fff;    \n"
"    background: qlineargradient(spread:pad, x1:0.523, y1:0, x2:0.625, y2:1, stop:0.5 rgba(9, 36, 126, 176), stop:1 rgba(0, 0, 0, 189));\n"
"}\n"
"\n"
"#player2Widget  {\n"
"    border: 2px solid #fff;    \n"
"    background: qlineargradient(spread:pad, x1:0.523, y1:0, x2:0.625, y2:1, stop:0.5 rgba(9, 36, 126, 176), stop:1 rgba(0, 0, 0, 189));\n"
"}\n"
"\n"
"\n"
"#tituloLabel {\n"
"    background: qlineargradient(spread:pad, x1:0.591273, y1:1, x2:0.511363, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(9, 36, 126, 255));\n"
"    border-radius: 30px;\n"
"    border: 4px solid #fff;\n"
"}\n"
"\n"
"#centralwidget {\n"
"    background: qlineargradient(spread:pad, x1:0.591273, y1:1, x2:0.511363, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(9, 36, 126, 255));\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.tituloLabel = QtWidgets.QLabel(self.centralwidget)
        self.tituloLabel.setGeometry(QtCore.QRect(293, 30, 780, 90))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.tituloLabel.setFont(font)
        self.tituloLabel.setStyleSheet("")
        self.tituloLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tituloLabel.setObjectName("tituloLabel")
        self.campeaoLabel = QtWidgets.QLabel(self.centralwidget)
        self.campeaoLabel.setGeometry(QtCore.QRect(466, 122, 434, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(28)
        self.campeaoLabel.setFont(font)
        self.campeaoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.campeaoLabel.setObjectName("campeaoLabel")
        self.player1Widget = QtWidgets.QWidget(self.centralwidget)
        self.player1Widget.setGeometry(QtCore.QRect(228, 190, 420, 440))
        self.player1Widget.setStyleSheet("#playerNomeLabel {\n"
"    background: qlineargradient(spread:pad, x1:0.552, y1:0, x2:0.557, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(9, 36, 126, 255));\n"
"    border: 2px solid #fff;\n"
"}")
        self.player1Widget.setObjectName("player1Widget")
        self.playerNomeLabel = QtWidgets.QLabel(self.player1Widget)
        self.playerNomeLabel.setGeometry(QtCore.QRect(0, 0, 420, 100))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(36)
        self.playerNomeLabel.setFont(font)
        self.playerNomeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.playerNomeLabel.setObjectName("playerNomeLabel")
        self.pontosLabel = QtWidgets.QLabel(self.player1Widget)
        self.pontosLabel.setGeometry(QtCore.QRect(85, 142, 250, 211))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(114)
        self.pontosLabel.setFont(font)
        self.pontosLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pontosLabel.setObjectName("pontosLabel")
        self.label = QtWidgets.QLabel(self.player1Widget)
        self.label.setGeometry(QtCore.QRect(72, 376, 276, 49))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.player2Widget = QtWidgets.QWidget(self.centralwidget)
        self.player2Widget.setGeometry(QtCore.QRect(718, 190, 420, 440))
        self.player2Widget.setStyleSheet("#playerNomeLabel_2 {\n"
"    background: qlineargradient(spread:pad, x1:0.552, y1:0, x2:0.557, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(9, 36, 126, 255));\n"
"    border: 2px solid #fff;\n"
"}")
        self.player2Widget.setObjectName("player2Widget")
        self.playerNomeLabel_2 = QtWidgets.QLabel(self.player2Widget)
        self.playerNomeLabel_2.setGeometry(QtCore.QRect(0, 0, 420, 100))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(36)
        self.playerNomeLabel_2.setFont(font)
        self.playerNomeLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.playerNomeLabel_2.setObjectName("playerNomeLabel_2")
        self.pontosLabel_2 = QtWidgets.QLabel(self.player2Widget)
        self.pontosLabel_2.setGeometry(QtCore.QRect(85, 142, 250, 211))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(114)
        self.pontosLabel_2.setFont(font)
        self.pontosLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.pontosLabel_2.setObjectName("pontosLabel_2")
        self.label_2 = QtWidgets.QLabel(self.player2Widget)
        self.label_2.setGeometry(QtCore.QRect(72, 376, 276, 49))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(36)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        
        self.sobre_btn = QtWidgets.QPushButton(self.centralwidget)
        self.sobre_btn.setGeometry(QtCore.QRect(538, 652, 290, 90))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.sobre_btn.setFont(font)
        self.sobre_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sobre_btn.setObjectName("sobre_btn")
        self.sobre_btn.setStyleSheet("#sobre_btn {\n"
"    background: qlineargradient(spread:pad, x1:0.552, y1:0, x2:0.557, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(9, 36, 126, 255));\n"
"    border: 2px solid #fff; border-radius: 30px; color: #fff;\n"
"}")
        
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("FinalWindow", "MainWindow"))
        self.sobre_btn.setText(_translate("FinalWindow", "Sobre"))
        self.tituloLabel.setText(_translate("FinalWindow", "Resultado"))
        self.campeaoLabel.setText(_translate("FinalWindow", "Player1 ganhou"))
        self.playerNomeLabel.setText(_translate("FinalWindow", "Player1"))
        self.pontosLabel.setText(_translate("FinalWindow", "80"))
        self.label.setText(_translate("FinalWindow", "Pontos"))
        self.playerNomeLabel_2.setText(_translate("FinalWindow", "Player2"))
        self.pontosLabel_2.setText(_translate("FinalWindow", "48"))
        self.label_2.setText(_translate("FinalWindow", "Pontos"))
