# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_inicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class InicialWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi()
        self.showMaximized()
    def setupUi(self):
        self.setObjectName("InicialWindow")
        self.resize(1366, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        self.setFont(font)
        self.setStyleSheet("\n"
"QWidget {\n"
"    background: qlineargradient(spread:pad, x1:0.489, y1:0, x2:0.488636, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(9, 36, 126, 255));\n"
"    color: #FFF;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background: qlineargradient(spread:pad, x1:0.489, y1:0, x2:0.488636, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(9, 36, 126, 255));\n"
"    border: 2px solid #FFF;\n"
"    border-radius: 30px;\n"
"}\n"
"\n"
"QPushButton::hover {\n"
"    background: qlineargradient(spread:pad, x1:0.494, y1:0.5, x2:0.5, y2:1, stop:0.335227 rgba(9, 34, 126, 228), stop:1 rgba(0, 0, 0, 0));\n"
"}")
        self.titulo = QtWidgets.QLabel(self)
        self.titulo.setGeometry(QtCore.QRect(183, 95, 1000, 270))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(84)
        font.setBold(True)
        font.setWeight(75)
        self.titulo.setFont(font)
        self.titulo.setStyleSheet("QLabel {\n"
"    background: qlineargradient(spread:pad, x1:0.489, y1:0, x2:0.488636, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(9, 36, 126, 255));\n"
"    border-radius: 30px;\n"
"    border: 4px solid #FFF;\n"
"}")
        self.titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.titulo.setObjectName("titulo")
        self.iniciar_btn = QtWidgets.QPushButton(self)
        self.iniciar_btn.setGeometry(QtCore.QRect(463, 427, 440, 110))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.iniciar_btn.setFont(font)
        self.iniciar_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.iniciar_btn.setObjectName("iniciar_btn")
        self.sobre_btn = QtWidgets.QPushButton(self)
        self.sobre_btn.setGeometry(QtCore.QRect(463, 587, 440, 110))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.sobre_btn.setFont(font)
        self.sobre_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sobre_btn.setObjectName("sobre_btn")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("InicialWindow", "Filosofia"))
        self.titulo.setText(_translate("InicialWindow", "Filosofia"))
        self.iniciar_btn.setText(_translate("InicialWindow", "Iniciar"))
        self.sobre_btn.setText(_translate("InicialWindow", "Sobre"))
