# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIs/ui_sobre.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class SobreWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi()
    def setupUi(self):
        self.setObjectName("MainWindow")
        self.setFixedSize(1366, 768)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.setFont(font)
        self.setStyleSheet("QWidget #centralwidget {\n"
"    background-color: qlineargradient(spread:pad, x1:0.528409, y1:0.454, x2:1, y2:1, stop:0.0511364 rgba(0, 0, 107, 255), stop:1 rgba(0, 0, 255, 255));\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #FFF;\n"
"    background: transparent;\n"
"}")
        self.centralwidget = QtWidgets.QWidget()
        self.centralwidget.setObjectName("centralwidget")
        self.label_sobre = QtWidgets.QLabel(self.centralwidget)
        self.label_sobre.setGeometry(QtCore.QRect(116, 60, 1135, 90))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(48)
        self.label_sobre.setFont(font)
        self.label_sobre.setStyleSheet("background-color: rgb(0, 0, 127);\n"
"color: rgb(255, 255, 255);\n"
"border: 2px solid #fff;\n"
"border-radius: 20px;")
        self.label_sobre.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sobre.setObjectName("label_sobre")
        self.label_tema = QtWidgets.QLabel(self.centralwidget)
        self.label_tema.setGeometry(QtCore.QRect(143, 250, 1101, 68))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(30)
        self.label_tema.setFont(font)
        self.label_tema.setStyleSheet("background: transparent;\n"
"color: rgb(255, 255, 255);")
        self.label_tema.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tema.setObjectName("label_tema")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(178, 473, 1016, 121))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(448, 380, 471, 41))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_sobre.setText(_translate("MainWindow", "Sobre"))
        self.label_tema.setText(_translate("MainWindow", "A virtude e a felicidade para Aristóteles e Sêneca"))
        self.label_4.setText(_translate("MainWindow", "Alunos: Caio Cabral,  Gloria Maria,  Gabriel Santos,  Italo Gabriel,  Marcelo Esaú,\n"
"Pablo Vinícius, Samuel Lázaro"))
        self.label_11.setText(_translate("MainWindow", "Professora: Euza Raquel de Sousa"))
